name: dev_release
 
on:
  push:
    branches:
      - zz_dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - run: npm install
 
      - name: Build
        run: npm run build_dev_release
 
      - name: Page Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dev_release
          publish_branch: dev_release