name: release_to_github_page
 
on:
  push:
    branches:
      - ${{ GITHUB_REF_NAME }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - run: npm install
 
      - name: Build
        run: npm run build2

      - name: Pack
        run: node pack_dev_release.js ${{ GITHUB_REF_NAME }}
 
      - name: Page Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dev_release
          publish_branch: dev_release